version: '3.7'
services:
  redis:
    image: redis
    container_name: usports_redis
    command: redis-server --port 6379
    hostname: redis
    ports:
      - 6379:6379
    restart: always

  mariadb:
    container_name: usports_mariadb
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MARIADB_DATABASE: usports
      MARIADB_USER: usports
      MARIADB_PASSWORD: a1234
      MARIADB_ROOT_PASSWORD: a1234
    networks:
      - backend
    restart: always

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
    networks:
      - backend

volumes:
  data: { }

networks:
  backend:
    name: backend
    driver: bridge
